[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
common = { path = "../common" }
clap_derive = "4.5.24"
clap = "4.5.27"
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
hex = "0.4"

[[bin]]
name = "client"
