[package]
name = "leaffs"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser = "0.14.0"
clap = { version = "4.5.16", features = ["cargo"] }
libc = "0.2.51"
env_logger = "0.11.5"
pkg-config = "0.3"
leafcore = { path = "../leafcore" }
tokio = { version = "1.40.0", features = ["full"] }