[package]
name = "leafd"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.12.0", features = ["v4", "rng"] }
tokio = { workspace = true }
leafcommon = { path = "../leafcommon" }
walkdir = "2.5.0"
clap = { workspace = true }
clap_derive = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-service = "0.8.0"
anyhow = "1.0.97"

[[bin]]
name = "leafd"
