[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

resolver = "2"

[workspace]
members = [
    "common",
    "client",
    "server",
]

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
client = { path = "client" }
server = { path = "server" }

[[bin]]
name = "leaf"
path = "src/main.rs"
