[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

resolver = "2"

[workspace]
members = [
    "common",
    "client",
    "server",
]

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
common = { path = "common" }

[lib]
name = "client"
path = "client/src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "server"
path = "server/src/main.rs"
