[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "leaflibrary",
    "leafdaemon",
    "leafclient",
]

[dependencies]
flate2 = "1.0.34"
kuznechik = "0.4.0"
rand = "0.8.5"
streebog = "0.10.2"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
reed-solomon-erasure = "6.0.0"
rayon = "1.10.0"
dirs = "5.0.1"
net2 = "0.2.39"
atomic_refcell = "0.1.13"
tokio = { version = "1.41.0", features = ["full"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
libc = "0.2.161"
num_cpus = "1.16.0"
clap = { version = "4.5.20", features = ["derive"] }
daemonize = "0.5.0"
bincode = "1.3.3"

[lib]
name = "leaflibrary"
path = "leaflibrary/src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "leafdaemon"
path = "leafdaemon/src/main.rs"

[[bin]]
name = "leafclient"
path = "leafclient/src/main.rs"
