[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "library",
    "client",
    "server",
]

[dependencies]
rayon = "1.10.0"
streebog = "0.10.2"
kuznechik = "0.4.0"
tokio = { version = "1.41.0", features = ["full"] }
rand = "0.8.5"
serde = { version = "1.0.213", features = ["derive"] }
reed-solomon-erasure = "6.0.0"
bincode = "1.3.3"
serde_json = "1.0.132"

[lib]
name = "leaf"
path = "library/src/lib.rs"
crate-type = ["rlib"]