[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.34"
kuznechik = "0.4.0"
rand = "0.8.5"
streebog = "0.10.2"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
reed-solomon-erasure = "6.0.0"
rayon = "1.10.0"
atomic_refcell = "0.1.13"
dirs = "5.0.1"
local-ip-address = "0.6.3"

[lib]
name = "leaf"
path = "src/lib.rs"
crate-type = ["cdylib"]
