[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
common = { path = "../common" }
serde = { version = "1.0.210", features = ["derive"] }
dirs = "5.0.1"
serde_json = "1.0.128"

[lib]
name = "server"
path = "src/lib.rs"
crate-type = ["rlib"]