[package]
name = "leaf-server"
version = "0.1.0"
edition = "2021"

[dependencies]
local-ip-address = "0.6.3"
tokio = { version = "1.40.0", features = ["full"] }
leaf-common = { path = "../leaf-common" }

[[bin]]
path = "src/main.rs"
