[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.34"
kuznechik = "0.4.0"
streebog = "0.10.2"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
reed-solomon-erasure = "6.0.0"
rayon = "1.10.0"
tokio = { version = "1.40.0", features = ["full"] }
dirs = "5.0.1"
rand = "0.8.5"

[lib]
name = "common"
crate-type = ["rlib"]
path = "src/lib.rs"