[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
bincode = "1.3.3"
kuznechik = "0.4.0"
streebog = "0.10.2"
reed-solomon-erasure = "6.0.0"
rayon = "1.10.0"
tokio = { workspace = true }

[lib]
name = "common"
crate-type = ["rlib"]
