[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.34"
kuznechik = "0.4.0"
streebog = "0.10.2"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
reed-solomon-erasure = "6.0.0"
rayon = "1.10.0"
rand = "0.8.5"
dirs = "5.0.1"
