[package]
name = "leafclient"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
leafcommon = { path = "../leafcommon" }
clap_derive = { workspace = true }
clap = { workspace = true }

[[bin]]
name = "leafclient"
